#!/bin/sh
set -e

composer install --no-interaction --optimize-autoloader
php yii migrate/up --interactive=0

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

exec "$@"
