version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Europe/Kiev

  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/usr/share/nginx/app
    working_dir: /usr/share/nginx/app
    depends_on:
      - mysql

  nginx:
    image: nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./app:/usr/share/nginx/app
      - ./conf/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - app
